set_value:
  name: Set value
  description: Sets val speed.

  fields:
    entity_id:
      description: Id of the entiy to set
      example: "sensor.something"
      required: true
    value:
      description: value to set
      example: "5"
      selector:
        number:
turn_on:
  name: Turn the 4heat on
  description: Sets val speed.
  fields:
    entity_id:
      description: Id of the entiy
      example: "sensor.something"
